### ISSUE TITLE
Invalid literal for int() with base 10: '.'

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/stranger#63]
I thought I had solved this in #59, but I think when I changed line 260  from `continue` to `repeat_res.extend([0])` the error consisted...

https://github.com/Clinical-Genomics/stranger/blob/06ab59eba05b07a7c4099c896ac16e46511d76ff/stranger/utils.py#L259-L260

Could you have a look? [HG002_Revio.vcf.gz](https://github.com/user-attachments/files/15513837/HG002_Revio.vcf.gz)

```
2024-05-31 14:40:51 stuart stranger.cli[41] INFO Running stranger version 0.9.0
  2024-05-31 14:40:51 stuart stranger.cli[41] INFO Parsing repeats file variant_catalog_grch38.json
  2024-05-31 14:40:51 stuart stranger.cli[41] INFO Vcf is zipped
  Traceback (most recent call last):
    File "/usr/local/bin/stranger", line 10, in <module>
      sys.exit(base_command())
               ^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
           ^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
      return f(get_current_context(), *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/stranger/cli.py", line 155, in cli
      repeat_data = get_repeat_info(variant_info, repeat_information)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/stranger/utils.py", line 209, in get_repeat_info
      repeat_res = get_trgt_repeat_res(variant_info, repeat_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/stranger/utils.py", line 269, in get_trgt_repeat_res
      pathologic_counts = int(allele)
                          ^^^^^^^^^^^
  ValueError: invalid literal for int() with base 10: '.'
```

**Comment by dnil** [comment]
Right, so this happens if for some reason TRGT does not set MC at all, only to a `.`. I'll make a simple workaround, but for the bigger picture, could you provide some info as to under what conditions this is happening? I have not yet seen it in an actual sample run? MC typically appears set to the reference repeat len if no deviating allele was found? Is it a "no call" when no allele had good enough quality? If so, we can just ignore it.

If its actual reference calls that happen for other reasons, we should perhaps parse the reference allele size from the repeat definitions and set it on the output. Or better yet, ask Egor and co to do so. 😊

**Comment by fellen31** [comment]
Thank you. This example happens when there are no reads in the region.

**Comment by dnil** [comment]
Gotcha. Ok, that is not going to happen very often, and I guess `0` is a good a size guesstimate as any if there are no reads at all mapping. 😸
